-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 05:29:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `author_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`authors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`authors` (
  `id` INT NOT NULL,
  `author_name` VARCHAR(45) NULL,
  `books_id` INT NOT NULL,
  PRIMARY KEY (`id`, `books_id`));


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_has_books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_has_books` (
  `users_user_id` INT NOT NULL,
  `books_book_id` INT NOT NULL,
  PRIMARY KEY (`users_user_id`, `books_book_id`));


-- -----------------------------------------------------
-- Table `mydb`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`favorites` ;

CREATE TABLE IF NOT EXISTS `mydb`.`favorites` (
  `users_id` INT NULL,
  `books_id` INT NULL);


-- -----------------------------------------------------
-- Table `mydb`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ratings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ratings` (
  `tconst` INT NOT NULL,
  `average_rating` VARCHAR(55) NULL,
  `number_of_votes` VARCHAR(55) NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `mydb`.`title_basics` (
  `tconst` INT NOT NULL,
  `primary_title` VARCHAR(55) NULL,
  `start_year` VARCHAR(55) NULL,
  `runtime` VARCHAR(55) NULL,
  `ratings_tconst` INT NOT NULL,
  PRIMARY KEY (`tconst`, `ratings_tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `genre_id` INT NOT NULL,
  `genre_name` VARCHAR(55) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`title_genres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`title_genres` (
  `title_basics_tconst` INT NOT NULL,
  `genres_genre_id` INT NOT NULL,
  PRIMARY KEY (`title_basics_tconst`, `genres_genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`` ;

CREATE TABLE IF NOT EXISTS `mydb`.`` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`title_genres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`title_genres` (
  `title_basics_tconst` INT NOT NULL,
  `genres_genre_id` INT NOT NULL,
  PRIMARY KEY (`title_basics_tconst`, `genres_genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`title_basics_has_ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`title_basics_has_ratings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`title_basics_has_ratings` (
  `title_basics_tconst` INT NOT NULL,
  `ratings_tconst` INT NOT NULL,
  PRIMARY KEY (`title_basics_tconst`, `ratings_tconst`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
