-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 19:55:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movies` ;

-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies` DEFAULT CHARACTER SET utf8 ;
USE `movies` ;

-- -----------------------------------------------------
-- Table `movies`.`authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`authors` ;

CREATE TABLE IF NOT EXISTS `movies`.`authors` (
  `author_id` INT NOT NULL,
  `author_name` VARCHAR(45) NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`books` ;

CREATE TABLE IF NOT EXISTS `movies`.`books` (
  `book_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  `authors_author_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `users_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`users` ;

CREATE TABLE IF NOT EXISTS `movies`.`users` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`favorites` ;

CREATE TABLE IF NOT EXISTS `movies`.`favorites` (
  `books_book_id` INT NOT NULL,
  `books_users_id` INT NOT NULL,
  `users_user_id` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`favorites` ;

CREATE TABLE IF NOT EXISTS `movies`.`favorites` (
  `books_book_id` INT NOT NULL,
  `books_users_id` INT NOT NULL,
  `users_user_id` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`favorites` ;

CREATE TABLE IF NOT EXISTS `movies`.`favorites` (
  `books_book_id` INT NOT NULL,
  `books_users_id` INT NOT NULL,
  `users_user_id` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`books_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`books_has_users` ;

CREATE TABLE IF NOT EXISTS `movies`.`books_has_users` (
  `books_book_id` INT NOT NULL,
  `books_users_id` INT NOT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`books_book_id`, `books_users_id`, `users_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `movies`.`title_basics` (
  `tconst` INT NOT NULL,
  `primary_title` VARCHAR(55) NOT NULL,
  `start_year` VARCHAR(55) NOT NULL,
  `runtime` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`ratings` ;

CREATE TABLE IF NOT EXISTS `movies`.`ratings` (
  `tconst` INT NOT NULL,
  `average_rating` VARCHAR(55) NULL,
  `number_of_votes` VARCHAR(55) NULL,
  `title_basics_tconst` INT NOT NULL,
  PRIMARY KEY (`tconst`, `title_basics_tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`genres` ;

CREATE TABLE IF NOT EXISTS `movies`.`genres` (
  `genre_id` INT NOT NULL,
  `genre_name` VARCHAR(55) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies`.`title_genres` ;

CREATE TABLE IF NOT EXISTS `movies`.`title_genres` (
  `title_basics_tconst` INT NOT NULL,
  `genres_genre_id` INT NOT NULL,
  PRIMARY KEY (`title_basics_tconst`, `genres_genre_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SHOW TABLES

DESCRIBE authors
DESCRIBE books
DESCRIBE books_has_users
DESCRIBE favorites
DESCRIBE genres
DESCRIBE ratings
DESCRIBE title_basics
DESCRIBE title_genres
DESCRIBE users

